#!/usr/bin/env node
/**
 * Generates src/components/ui/icons.ts from lucide-static (ISC licence).
 * Add an entry to ICONS (our name → Lucide name) and run `npm run icons`.
 * Inline SVG keeps pages free of icon fonts and extra requests.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ICONS = {
  cart: 'shopping-cart',
  'credit-card': 'credit-card',
  eye: 'eye',
  hand: 'hand',
  package: 'package',
  'trending-down': 'trending-down',
  sparkles: 'sparkles',
  truck: 'truck',
  refresh: 'refresh-cw',
  gift: 'gift',
  mouse: 'mouse-pointer-click',
  globe: 'globe',
  mail: 'mail',
  shield: 'shield-check',
  tag: 'tag',
  layout: 'layout-template',
  split: 'split',
  users: 'users',
  calendar: 'calendar',
  wand: 'wand-sparkles',
  languages: 'languages',
  'badge-check': 'badge-check',
  flame: 'flame',
  filter: 'filter',
  server: 'server',
  store: 'store',
  activity: 'activity',
  workflow: 'workflow',
  ticket: 'ticket',
  bell: 'bell',
  star: 'star',
  chart: 'chart-column',
  'chart-line': 'chart-line',
  send: 'send',
  smartphone: 'smartphone',
  monitor: 'monitor',
  check: 'check',
  x: 'x',
  minus: 'minus',
  plus: 'plus',
  'arrow-right': 'arrow-right',
  'arrow-left': 'arrow-left',
  'chevron-down': 'chevron-down',
  menu: 'menu',
  search: 'search',
  rss: 'rss',
  clock: 'clock',
  external: 'external-link',
  quote: 'quote',
  book: 'book-open',
  support: 'life-buoy',
  zap: 'zap',
  chat: 'message-circle',
  handshake: 'handshake',
  rocket: 'rocket',
  trophy: 'trophy',
  code: 'code-xml',
  dollar: 'circle-dollar-sign',
  percent: 'percent',
  timer: 'timer',
  target: 'target',
  bot: 'bot',
  inbox: 'inbox',
  settings: 'settings-2',
  layers: 'layers',
  heart: 'heart',
  'calendar-days': 'calendar-days',
  bolt: 'zap',
};

const dir = path.resolve(import.meta.dirname, '../node_modules/lucide-static/icons');
const entries = Object.entries(ICONS).map(([name, lucide]) => {
  const svg = readFileSync(path.join(dir, `${lucide}.svg`), 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();
  return `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`;
});

writeFileSync(
  path.resolve(import.meta.dirname, '../src/components/ui/icons.ts'),
  `// Generated by scripts/build-icons.mjs from lucide-static (ISC). Do not edit by hand.\nexport const icons = {\n${entries.join('\n')}\n} as const;\n\nexport type IconName = keyof typeof icons;\n`,
);
console.log(`Wrote ${entries.length} icons`);
